# Copy to application-local.conf and customize, or set env vars (they take priority).
database {
    jdbcUrl = "jdbc:postgresql://localhost:5432/<insert_your_db_name>"
    user = "<insert_your_db_user>"
    password = "<insert_your_db_password>"
}

jwt {
    secret = "<insert_your_long_random_secret_min_32_chars>"
}
